package com.rodionov.mishka.flagmemorine.logic;

import com.rodionov.mishka.flagmemorine.R;

import java.util.HashMap;
import java.util.Random;

/**
 * Created by Lab1 on 23.05.2018.
 */

public class Facts {

    public static String randomRussiaFacts(){
        Random rnd = new Random();
        int resource = rnd.nextInt(russia.length);
        return russia[resource];
    }

    private static void loadCountryFactsMap(){
        countryFactsMap = new HashMap<>();
        countryFactsMap.put(R.drawable.russia, russia);

    }

    public static String randomCountryFacts(){
        loadCountryFactsMap();
        Random rnd = new Random();
        int resource = rnd.nextInt(countryResources.length);
        String[] country = countryFactsMap.get(resource);
        int index = rnd.nextInt(country.length);
        return country[index];
    }

    private static HashMap<Integer, String[]> countryFactsMap;

    private static String[] russia = {
            "Russia - is a biggest country of the world.",
            "Moscow - is a capital of Russian Federation.",
            "Baikal - is a deepest lake of the world."
    };

    private static String[] afghanistan = {};

    private static int[] countryResources = {
                R.drawable.afghanistan,
//              R.drawable.aland),
                R.drawable.albania,
                R.drawable.algeria,
                R.drawable.american_samoa,
                R.drawable.andorra,
                R.drawable.angola,
                R.drawable.anguilla,
                R.drawable.antarctica,
                R.drawable.antigua_and_barbuda,
                R.drawable.argentina,
                R.drawable.armenia,
                R.drawable.aruba,
                R.drawable.australia,
                R.drawable.austria,
                R.drawable.azerbaijan,
                R.drawable.bahamas,
                R.drawable.bahrain,
                R.drawable.bangladesh,
                R.drawable.barbados,
//              R.drawable.basque_country,
                R.drawable.belarus,
                R.drawable.belgium,
                R.drawable.belize,
                R.drawable.benin,
                R.drawable.bermuda,
                R.drawable.bhutan,
                R.drawable.bolivia,
//              R.drawable.bosnia_and_herzegovina,
                R.drawable.botswana,
                R.drawable.brazil,
                R.drawable.british_antarctic_territory,
                R.drawable.british_virgin_islands,
                R.drawable.brunei,
                R.drawable.bulgaria,
                R.drawable.burkina_faso,
                R.drawable.burundi,
                R.drawable.cambodia,
                R.drawable.cameroon,
                R.drawable.canada,
//              R.drawable.canary_islands,
                R.drawable.cape_verde,
                R.drawable.cayman_islands,
                R.drawable.central_african_republic,
                R.drawable.chad,
                R.drawable.chile,
                R.drawable.china,
                R.drawable.christmas_island,
//              R.drawable.cocos_keeling_islands,
                R.drawable.colombia,
//              R.drawable.commonwealth,
                R.drawable.comoros,
                R.drawable.cook_islands,
                R.drawable.costa_rica,
//              R.drawable.cote_divoire,
//              R.drawable.croatia,
                R.drawable.cuba,
                R.drawable.curacao,
                R.drawable.cyprus,
                R.drawable.czech_republic,
//              R.drawable.democratic_republic_of_the_congo,
                R.drawable.denmark,
                R.drawable.djibouti,
                R.drawable.dominica,
                R.drawable.dominican_republic,
                R.drawable.east_timor,
                R.drawable.ecuador,
                R.drawable.egypt,
                R.drawable.el_salvador,
                R.drawable.england,
                R.drawable.equatorial_guinea,
                R.drawable.eritrea,
                R.drawable.estonia,
                R.drawable.ethiopia,
                R.drawable.european_union,
                R.drawable.falkland_islands,
//              R.drawable.faroes,
                R.drawable.fiji,
                R.drawable.finland,
                R.drawable.france,
                R.drawable.french_polynesia,
                R.drawable.french_southern_territories,
                R.drawable.gabon,
                R.drawable.gambia,
                R.drawable.georgia,
                R.drawable.germany,
                R.drawable.ghana,
                R.drawable.gibraltar,
//              R.drawable.gosquared,
                R.drawable.greece,
                R.drawable.greenland,
                R.drawable.grenada,
                R.drawable.guam,
                R.drawable.guatemala,
                R.drawable.guernsey,
                R.drawable.guinea_bissau,
                R.drawable.guinea,
                R.drawable.guyana,
                R.drawable.haiti,
                R.drawable.honduras,
                R.drawable.hong_kong,
                R.drawable.hungary,
                R.drawable.iceland,
                R.drawable.india,
                R.drawable.indonesia,
                R.drawable.iran,
                R.drawable.iraq,
                R.drawable.ireland,
                R.drawable.isle_of_man,
                R.drawable.israel,
                R.drawable.italy,
                R.drawable.jamaica,
                R.drawable.japan,
                R.drawable.jersey,
                R.drawable.jordan,
                R.drawable.kazakhstan,
                R.drawable.kenya,
                R.drawable.kiribati,
                R.drawable.kosovo,
                R.drawable.kuwait,
                R.drawable.kyrgyzstan,
                R.drawable.laos,
                R.drawable.latvia,
                R.drawable.lebanon,
                R.drawable.lesotho,
                R.drawable.liberia,
                R.drawable.libya,
                R.drawable.liechtenstein,
                R.drawable.lithuania,
                R.drawable.luxembourg,
                R.drawable.macau,
                R.drawable.macedonia,
                R.drawable.madagascar,
                R.drawable.malawi,
                R.drawable.malaysia,
                R.drawable.maldives,
                R.drawable.mali,
                R.drawable.malta,
//              R.drawable.mars,
                R.drawable.marshall_islands,
                R.drawable.martinique,
                R.drawable.mauritania,
                R.drawable.mauritius,
                R.drawable.mayotte,
                R.drawable.mexico,
                R.drawable.micronesia,
                R.drawable.moldova,
                R.drawable.monaco,
                R.drawable.mongolia,
                R.drawable.montenegro,
                R.drawable.montserrat,
                R.drawable.morocco,
                R.drawable.mozambique,
                R.drawable.myanmar,
//              R.drawable.nagorno_karabakh,
                R.drawable.namibia,
//              R.drawable.nato,
                R.drawable.nauru,
                R.drawable.nepal,
                R.drawable.netherlands_antilles,
                R.drawable.netherlands,
                R.drawable.new_caledonia,
                R.drawable.new_zealand,
                R.drawable.nicaragua,
                R.drawable.niger,
                R.drawable.nigeria,
                R.drawable.niue,
                R.drawable.norfolk_island,
                R.drawable.north_korea,
//              R.drawable.northern_cyprus,
                R.drawable.northern_mariana_islands,
                R.drawable.norway,
                R.drawable.olympics,
                R.drawable.oman,
                R.drawable.pakistan,
                R.drawable.palau,
//              R.drawable.palestine,
                R.drawable.panama,
                R.drawable.papua_new_guinea,
                R.drawable.paraguay,
                R.drawable.peru,
                R.drawable.philippines,
//              R.drawable.pitcairn_islands,
                R.drawable.poland,
                R.drawable.portugal,
                R.drawable.puerto_rico,
                R.drawable.qatar,
//             R.drawable.red_cross,
//              R.drawable.republic_of_the_congo,
                R.drawable.romania,
                R.drawable.russia,
                R.drawable.rwanda,
                R.drawable.saint_barthelemy,
                R.drawable.saint_helena,
                R.drawable.saint_kitts_and_nevis,
                R.drawable.saint_lucia,
                R.drawable.saint_martin,
                R.drawable.svg,
                R.drawable.samoa,
                R.drawable.san_marino,
                R.drawable.sao_tome_and_principe,
                R.drawable.saudi_arabia,
                R.drawable.scotland,
                R.drawable.senegal,
                R.drawable.serbia,
                R.drawable.seychelles,
                R.drawable.sierra_leone,
                R.drawable.singapore,
                R.drawable.slovakia,
                R.drawable.slovenia,
                R.drawable.solomon_islands,
                R.drawable.somalia,
//              R.drawable.somaliland,
                R.drawable.south_africa,
//              R.drawable.south_georgia_and_the_south_sandwich_islands,
//              R.drawable.south_korea,
//              R.drawable.south_ossetia,
                R.drawable.south_sudan,
                R.drawable.spain,
                R.drawable.sri_lanka,
                R.drawable.sudan,
                R.drawable.suriname,
                R.drawable.swaziland,
                R.drawable.sweden,
                R.drawable.switzerland,
                R.drawable.syria,
                R.drawable.taiwan,
                R.drawable.tajikistan,
                R.drawable.tanzania,
                R.drawable.thailand,
                R.drawable.togo,
                R.drawable.tokelau,
                R.drawable.tonga,
                R.drawable.trinidad_and_tobago,
                R.drawable.tunisia,
                R.drawable.turkey,
                R.drawable.turkmenistan,
                R.drawable.turks_and_caicos_islands,
                R.drawable.tuvalu,
                R.drawable.uganda,
                R.drawable.ukraine,
                R.drawable.united_arab_emirates,
                R.drawable.united_kingdom,
//              R.drawable.united_nations,
                R.drawable.united_states,
                R.drawable.unknown,
                R.drawable.uruguay,
//              R.drawable.us_virgin_islands,
                R.drawable.uzbekistan,
                R.drawable.vanuatu,
                R.drawable.vatican_city,
                R.drawable.venezuela,
                R.drawable.vietnam,
                R.drawable.wales,
                R.drawable.wallis_and_futuna,
                R.drawable.western_sahara,
                R.drawable.yemen,
                R.drawable.zambia,
                R.drawable.zimbabwe
    };
}
